services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug